spring:
  datasource:
    url: jdbc:mysql://localhost/individual_dev
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
      time-between-eviction-runs-millis: 7200000
  jpa:
    show-sql: false
    properties:
      hibernate:
        query:
          plan_cache_max_size: 32
          plan_parameter_metadata_max_size: 64
